# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faceData.proto
# Protobuf Python Version: 4.24.0-main
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import unityQuaternion_pb2 as unityQuaternion__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x66\x61\x63\x65\x44\x61ta.proto\x1a\x15unityQuaternion.proto\"\x90\x01\n\x08\x46\x61\x63\x65\x44\x61ta\x12&\n\x0cheadRotation\x18\x01 \x01(\x0b\x32\x10.UnityQuaternion\x12-\n\x0b\x62lendShapes\x18\x02 \x03(\x0b\x32\x18.FaceData.BlendShapeData\x1a-\n\x0e\x42lendShapeData\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02\x42\x1f\xaa\x02\x1cHSR.MotionCapture.Net.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'faceData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034HSR.MotionCapture.Net.Protos'
  _globals['_FACEDATA']._serialized_start=42
  _globals['_FACEDATA']._serialized_end=186
  _globals['_FACEDATA_BLENDSHAPEDATA']._serialized_start=141
  _globals['_FACEDATA_BLENDSHAPEDATA']._serialized_end=186
# @@protoc_insertion_point(module_scope)
