# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: packetCode.proto
# Protobuf Python Version: 4.24.0-main
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10packetCode.proto*\x88\x01\n\nPacketCode\x12\x08\n\x04NONE\x10\x00\x12\x0f\n\x0bQUIT_NOTIFY\x10\x01\x12\x12\n\x0eHEART_BEAT_REQ\x10\x04\x12\x12\n\x0eHEART_BEAT_RSP\x10\x05\x12\r\n\tFACE_DATA\x10\x06\x12\r\n\tPOSE_DATA\x10\x07\x12\r\n\tHAND_DATA\x10\x08\"\x04\x08\x02\x10\x02\"\x04\x08\x03\x10\x03\x42\x1f\xaa\x02\x1cHSR.MotionCapture.Net.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packetCode_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034HSR.MotionCapture.Net.Protos'
  _globals['_PACKETCODE']._serialized_start=21
  _globals['_PACKETCODE']._serialized_end=157
# @@protoc_insertion_point(module_scope)
