# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: poseData.proto
# Protobuf Python Version: 4.24.0-main
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import unityVector3_pb2 as unityVector3__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eposeData.proto\x1a\x12unityVector3.proto\",\n\x08PoseData\x12 \n\tlandmarks\x18\x01 \x03(\x0b\x32\r.UnityVector3B\x1f\xaa\x02\x1cHSR.MotionCapture.Net.Protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'poseData_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\034HSR.MotionCapture.Net.Protos'
  _globals['_POSEDATA']._serialized_start=38
  _globals['_POSEDATA']._serialized_end=82
# @@protoc_insertion_point(module_scope)
